#!/bin/bash
# Online MTP Finetuning Script
#
# Runs the full online MTP finetuning pipeline: convert native MTP head,
# data preparation, vLLM server launch, and training (with hidden states
# generated on-the-fly from the live server). After training, stitches
# finetuned weights back into the verifier checkpoint.
#
# Unlike Eagle-3, DFlash, or P-EAGLE which train draft models from scratch,
# MTP finetuning starts from the model's native MTP head (converted to
# speculators format) and finetunes it on domain-specific data.
#
# Usage: Copy this script, modify the configuration variables below, then run:
#   bash examples/train/mtp_qwen3_5_9b_gsm8k_online.sh
#
# For a detailed walkthrough, see
# https://docs.vllm.ai/projects/speculators/en/latest/user_guide/tutorials/train_mtp_online/

### Example E2E run for Qwen3.5-9B on GSM8K ###

# Timing (on 2x NVIDIA H100 80GB GPUs)
# MTP Conversion: 26 seconds
# Data Preprocessing: 31 seconds
# vLLM Server Startup: 114 seconds (1 min 54 secs)
# Training (3 epochs): 256 seconds (4 mins 16 secs)
# Stitching: 42 seconds
# Total: 469 seconds (7 mins 49 secs)
#
# Results (3 generic prompts, 50 output tokens):
# acceptance rate: 89.36%
# acceptance length: 3.23
# per-position acceptance:
#   position 0: 89.36%
#   position 1: 72.34%
#   position 2: 61.70%

set -euo pipefail

# ============ Configuration ============
MODEL="Qwen/Qwen3.5-9B"

# MTP requires training data generated by the target model itself. We use a
# pre-regenerated dataset from HuggingFace. To create your own, see:
# https://docs.vllm.ai/projects/speculators/en/latest/user_guide/tutorials/response_regeneration/
DATASET="inference-optimization/Qwen3.5-9B-responses"
DATASET_FILE="gsm8k.jsonl"
OUTPUT_DIR="./output"
CONVERTED_DIR="$OUTPUT_DIR/converted_mtp"
STITCHED_DIR="$OUTPUT_DIR/stitched"
VLLM_PORT=8000
MAX_SAMPLES=5000
SEQ_LENGTH=8192
EPOCHS=3
LR=1e-4
STEP_WEIGHT_BETA=0.6              # Exponential decay factor for per-step loss weights

# GPU assignments (online training needs separate GPUs for vLLM and training)
VLLM_GPU="0"
TRAIN_GPU="1"
# =======================================

# Step 1: Convert native MTP head to speculators format
echo "=== Step 1: Converting native MTP head ==="
python -c "
from speculators.convert import convert_model
convert_model(
    model='$MODEL',
    verifier='$MODEL',
    algorithm='mtp',
    output_path='$CONVERTED_DIR',
    num_speculative_steps=3,
)
"

# Step 2: Download regenerated dataset and prepare data
echo "=== Step 2: Downloading dataset and preparing data ==="
DATASET_DIR="$OUTPUT_DIR/dataset"
hf download "$DATASET" "$DATASET_FILE" --repo-type dataset --local-dir "$DATASET_DIR"

python scripts/prepare_data.py \
    --model "$MODEL" \
    --data "$DATASET_DIR/$DATASET_FILE" \
    --max-samples "$MAX_SAMPLES" \
    --output "$OUTPUT_DIR" \
    --seq-length "$SEQ_LENGTH"

# Step 3: Launch vLLM server in the background
echo "=== Step 3: Launching vLLM server ==="
CUDA_VISIBLE_DEVICES="$VLLM_GPU" python scripts/launch_vllm.py "$MODEL" \
    --target-layer-ids 32 \
    -- --port "$VLLM_PORT" &
VLLM_PID=$!

# Ensure vLLM is cleaned up on exit
cleanup() {
    echo "Stopping vLLM server..."
    kill "$VLLM_PID" 2>/dev/null || true
    wait "$VLLM_PID" 2>/dev/null || true
}
trap cleanup EXIT

echo "Waiting for vLLM server to be ready..."
until curl -sf "http://localhost:${VLLM_PORT}/health" > /dev/null 2>&1; do
    sleep 2
done
echo "vLLM server ready."

# Step 4: Train against the live vLLM server
echo "=== Step 4: Training ==="
CUDA_VISIBLE_DEVICES="$TRAIN_GPU" python \
    scripts/train.py \
    --verifier-name-or-path "$MODEL" \
    --data-path "$OUTPUT_DIR" \
    --vllm-endpoint "http://localhost:${VLLM_PORT}/v1" \
    --save-path "$OUTPUT_DIR/checkpoints" \
    --speculator-type mtp \
    --from-pretrained "$CONVERTED_DIR" \
    --target-layer-ids 32 \
    --step-weight-beta "$STEP_WEIGHT_BETA" \
    --epochs "$EPOCHS" \
    --lr "$LR" \
    --total-seq-len "$SEQ_LENGTH" \
    --on-missing generate \
    --on-generate delete

# Step 5: Stitch finetuned weights back into the verifier
echo "=== Step 5: Stitching finetuned weights ==="
python scripts/stitch_mtp.py \
    "$OUTPUT_DIR/checkpoints/checkpoint_best" \
    "$MODEL" \
    --output-path "$STITCHED_DIR"

echo "Done. Stitched checkpoint saved to $STITCHED_DIR/"
echo "Deploy with: vllm serve $STITCHED_DIR --speculative-config '{\"method\":\"mtp\",\"num_speculative_tokens\":3}' --no-enable-chunked-prefill"
echo "See https://recipes.vllm.ai/ for more deployment options."
