#!/bin/bash
# Reproduce Draft-OPD's "DFlash + OPD-data SFT" baseline (paper Fig. 4) with speculators.
#
# Stage 1 = z-lab/Qwen3-8B-DFlash-b16 (public DFlash SFT checkpoint).
# Stage 2 = continue SFT on the 16k-prompt OPD pool regenerated by Qwen3-8B
#           (shanjiaz/opd-qwen3-8b-regen, produced with this repo's regen script:
#           pre-tokenized rows with input_ids + loss_mask, sampled at Qwen3
#           defaults temp 0.6 / top_p 0.95 / top_k 20, max_tokens 8192).
#
# Hyperparameters follow the paper's SFT framework recipe
# (SpecForge examples/run_qwen3_8b_dflash_online.sh): AdamW lr 6e-4, wd 0.0,
# cosine schedule with 4% warmup, grad clip 1.0 (speculators clips at 1.0
# unconditionally), loss decay gamma 7.0, 512 anchors per ~3k-token sequence,
# block size 16. The intended difference vs the reference is vLLM (here) vs
# SGLang (SpecForge) serving the target for hidden states.
#
# Batch semantics differ by construction: SpecForge steps on 4 padded seqs/GPU
# (8 GPUs -> 32 seqs, ~60-90k tokens/step); speculators packs ~8192 tokens/GPU
# per step. 8 training GPUs lands in the same tokens/step ballpark; fewer GPUs
# means a proportionally smaller effective batch (no grad-accumulation knob).

set -euo pipefail

# ============ Configuration ============
MODEL="Qwen/Qwen3-8B"
STAGE1_CKPT="z-lab/Qwen3-8B-DFlash-b16"
DATASET_REPO="shanjiaz/opd-qwen3-8b-regen"
DATASET_FILE="opd_Qwen3-8B.jsonl"

WORK_DIR="./output/opd_qwen3_8b_stage2"
CONVERTED="$WORK_DIR/dflash_b16_speculators"
DATA_DIR="$WORK_DIR/data"
HS_PATH="/tmp/hidden_states_opd"
VLLM_PORT=8000

# Covers prompt + up-to-8192-token responses without truncation. The SpecForge
# reference truncates at 3072; set 3072 here to also match its truncation.
SEQ_LENGTH=8192
EPOCHS=8              # OPD-stage budget the Fig.4 baseline is compared under
LR=6e-4               # SFT recipe (the OPD *stage* used 3e-4; that's verl, not SFT)
WARMUP_RATIO=0.04
MAX_ANCHORS=2048      # = SpecForge 512 anchors/seq x batch 4, per GPU-step
DECAY_GAMMA=7.0       # SpecForge suggested gamma for block_size=16
# Data is sampled (temp 0.6), so KL to the target logits is the faithful
# distillation objective; 'ce' (CE on argmax of target logits) is the exact
# SpecForge token-CE analogue only for greedy data.
LOSS_FN=kl_div
# z-lab config target_layer_ids [1,9,17,25,33] +1 for speculators' indexing
# (z-lab reads hidden_states[i+1]; the converter applies the same shift).
TARGET_LAYER_IDS="2 10 18 26 34"

# Set VLLM_PYTHON if vLLM lives in a different venv than speculators.
VLLM_PYTHON="${VLLM_PYTHON:-python}"
# One 8-GPU node: 2 GPUs serve hidden states, 6 train (~49k tokens/step,
# closest match to the reference's ~60-90k with vLLM colocated).
VLLM_GPUS="0,1"
TRAIN_GPUS="2,3,4,5,6,7"
NUM_TRAIN_GPUS=6
DP_SIZE=2
# On GB10/Spark use sdpa instead: flex-attention backward OOMs there at draft
# hidden >= 2560 (this draft is 4096).
DRAFT_ATTN_IMPL="${DRAFT_ATTN_IMPL:-simple_flex_attention}"
LOGGER=""             # e.g. wandb / trackio / tensorboard
# =======================================

mkdir -p "$WORK_DIR"

# Step 0: Fetch the regenerated dataset (cached by huggingface_hub).
echo "=== Step 0: Fetching $DATASET_REPO/$DATASET_FILE ==="
DATASET_LOCAL=$(python - <<PY
from huggingface_hub import hf_hub_download
print(hf_hub_download("$DATASET_REPO", "$DATASET_FILE", repo_type="dataset"))
PY
)
echo "Dataset: $DATASET_LOCAL"

# Step 1: Convert the z-lab checkpoint to speculators format. The `speculators
# convert` CLI does not list dflash yet, so call the Python API. Conversion
# fills embed_tokens/lm_head/verifier_norm from the verifier weights.
if [[ ! -f "$CONVERTED/config.json" ]]; then
    echo "=== Step 1: Converting $STAGE1_CKPT ==="
    python -c "
from speculators.convert import convert_model
convert_model(
    model='$STAGE1_CKPT',
    verifier='$MODEL',
    algorithm='dflash',
    output_path='$CONVERTED',
    validate_device='cpu',
)"
else
    echo "=== Step 1: Converted checkpoint exists, skipping ==="
fi

# Step 2: Prepare data. Rows are pre-tokenized (input_ids + loss_mask), so this
# is a passthrough that only truncates to SEQ_LENGTH and records token stats.
echo "=== Step 2: Preparing data ==="
python scripts/prepare_data.py \
    --model "$MODEL" \
    --data "$DATASET_LOCAL" \
    --output "$DATA_DIR" \
    --seq-length "$SEQ_LENGTH"

# Step 3: Launch the target for online hidden-state generation.
echo "=== Step 3: Launching vLLM ==="
CUDA_VISIBLE_DEVICES="$VLLM_GPUS" "$VLLM_PYTHON" scripts/launch_vllm.py "$MODEL" \
    --target-layer-ids $TARGET_LAYER_IDS \
    --hidden-states-path "$HS_PATH" \
    -- --data-parallel-size "$DP_SIZE" --port "$VLLM_PORT" &
VLLM_PID=$!

cleanup() {
    echo "Stopping vLLM server..."
    kill "$VLLM_PID" 2>/dev/null || true
    wait "$VLLM_PID" 2>/dev/null || true
}
trap cleanup EXIT

echo "Waiting for vLLM server to be ready..."
until curl -sf "http://localhost:${VLLM_PORT}/health" > /dev/null 2>&1; do
    sleep 2
done

# Step 4: Stage-2 SFT from the converted checkpoint. No --d2t/--t2d (full-vocab
# draft) and no --target-layer-ids/--block-size (both come from the converted
# config: layers [2,10,18,26,34], block 16, mask token 151669).
echo "=== Step 4: Training stage two ==="
EXTRA_ARGS=()
[[ -n "$LOGGER" ]] && EXTRA_ARGS+=(--logger "$LOGGER")
CUDA_VISIBLE_DEVICES="$TRAIN_GPUS" torchrun \
    --standalone --nproc_per_node "$NUM_TRAIN_GPUS" \
    scripts/train.py \
    --verifier-name-or-path "$MODEL" \
    --speculator-type dflash \
    --from-pretrained "$CONVERTED" \
    --data-path "$DATA_DIR" \
    --hidden-states-path "$HS_PATH" \
    --vllm-endpoint "http://localhost:${VLLM_PORT}/v1" \
    --on-missing generate \
    --on-generate delete \
    --save-path "$WORK_DIR/checkpoints" \
    --save-best \
    --epochs "$EPOCHS" \
    --optimizer adamw \
    --lr "$LR" \
    --weight-decay 0.0 \
    --scheduler-type cosine \
    --scheduler-warmup-ratio "$WARMUP_RATIO" \
    --total-seq-len "$SEQ_LENGTH" \
    --max-anchors "$MAX_ANCHORS" \
    --dflash-decay-gamma "$DECAY_GAMMA" \
    --loss-fn "$LOSS_FN" \
    --noise-std 0.0 \
    --draft-attn-impl "$DRAFT_ATTN_IMPL" \
    --run-name opd-qwen3-8b-stage2-sft \
    "${EXTRA_ARGS[@]}"

echo "Done. Checkpoints saved to $WORK_DIR/checkpoints/"
