CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 accelerate launch -m  --mixed_precision=bf16 --use_deepspeed --main_process_port  29501 --num_processes 8 train.main_train_full_gradient_calc_eagle3 \
    --basepath ~/path/to/verifier/model \
    --tmpdir dataDirectory \
    --cpdir Eagle3 \
    --configpath train/llama3_8_B.json \
    --epoch 4 \
    --bs 1 \
    --topk_w 0 \
    --topk 1 \
    --lr 8e-5 \
    --forward_num_total 3 \
