[build-system]
requires = ["setuptools >= 82.0.1", "setuptools-git-versioning>=2.0,<3", "packaging"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
include = ["*"]

[project]
name = "hs-connectors"
description = "Pluggable backends for transferring hidden states between vLLM and Speculators during online and offline training."
dynamic = ["version"]
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.10"
keywords = [
    "hidden states",
    "speculative decoding",
    "speculators",
    "vllm",
    "llm",
    "inference",
    "training",
    "online training",
    "offline training",
    "safetensors",
    "mooncake",
    "distributed training"
]
license = "Apache-2.0"
license-files = ["LICENSE"]
authors = [ { name = "Red Hat"} ]
dependencies = [
    "safetensors",
    "torch",
]
