nav:
  - Home: index.md
  - User Guide:
    - user_guide/README.md
    - Getting Started: user_guide/getting_started.md
    - Features:
      - user_guide/features/README.md
      - Response Regeneration: user_guide/features/response_regeneration.md
      - Prepare Data: user_guide/features/prepare_data.md
      - Offline Hidden States Generation: user_guide/features/offline_hidden_states.md
      - Training: user_guide/features/training.md
      - Conversion: user_guide/features/conversion.md
    - Algorithms:
      - user_guide/algorithms/README.md
      - Eagle3: user_guide/algorithms/eagle3.md
      - Dflash: user_guide/algorithms/dflash.md
      - Decision Guide: user_guide/algorithms/decision_guide.md
    - Tutorials:
      - user_guide/tutorials/README.md
      - Train Eagle3 Model Online: user_guide/tutorials/train_eagle3_online.md
      - Train Eagle3 Model Offline: user_guide/tutorials/train_eagle3_offline.md
      - Train Dflash Model Online: user_guide/tutorials/train_dflash_online.md
      - Response Regeneration: user_guide/tutorials/response_regeneration.md
      - Evaluating Model Performance: user_guide/tutorials/evaluating_performance.md
      - Convert Eagle3 Model: user_guide/tutorials/convert_eagle3.md
      - Serve in vLLM: user_guide/tutorials/serve_vllm.md
    - Troubleshooting: user_guide/troubleshooting.md
  - Developer Guide:
    - developer/index.md
    - Contributing Guide: developer/contributing.md
    - Code of Conduct: developer/code_of_conduct.md
    - Add New Spec Decode Algorithm: developer/add_algorithm.md
    - Design Documents: developer/design_docs.md
  - Roadmap: roadmap.md
  - API Reference:
    - api/README.md
    - reference/speculators
  - CLI Reference:
    - cli/README.md
  - Community: community.md
