name: Development

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

env:
  UV_TORCH_BACKEND: "auto"
  HF_TOKEN: ${{ secrets.HF_RED_HAT_READ_ONLY }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ready-check:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - name: Check PR label and author merge count
      uses: actions/github-script@v9
      with:
        script: |
          const { data: pr } = await github.rest.pulls.get({
            ...context.repo,
            pull_number: context.payload.pull_request.number,
          });

          const hasReadyLabel = pr.labels.some(l => l.name === 'ready');

          if (hasReadyLabel) {
            core.info('Check passed: PR has the ready label.');
          } else {
            core.setFailed("PR must have the 'ready' label to trigger test jobs.");
          }

  unit-tests:
    needs: ready-check
    runs-on: ibm-wdc-k8s-vllm-h100-solo
    strategy:
      matrix:
        python: ["3.10", "3.13"]
        transformers: ["<5.0.0", ""]
        exclude:
            - python: "3.13"
              transformers: "<5.0.0"
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-test-env
        with:
          python-version: ${{ matrix.python }}
          transformers-version: ${{ matrix.transformers }}
      - name: Run unit tests
        run: python -m pytest -ra tests/unit

  integration-tests:
    needs: ready-check
    runs-on: ibm-wdc-k8s-vllm-h100-solo
    strategy:
      matrix:
        python: ["3.10", "3.13"]
        transformers: ["<5.0.0", ""]
        exclude:
            - python: "3.13"
              transformers: "<5.0.0"
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-test-env
        with:
          python-version: ${{ matrix.python }}
          transformers-version: ${{ matrix.transformers }}
      - name: Run integration tests
        run: python -m pytest -ra tests/integration
